package ru.r2cloud.jradio.hunity;

public enum SampleTimeRelative {

	LESS_THAN_5_SECONDS, LESS_THAN_10_SECONDS, LESS_THAN_20_SECONDS, LESS_THAN_30_SECONDS, LESS_THAN_40_SECONDS, LESS_THAN_60_SECONDS, OLDER_THAN_60_SECONDS, LESS_THAN_120_SECONDS, OLDER_THAN_120_SECONDS, OLDER_THAN_125_SECONDS, INVALID

}
